version: "3.8"
services:
  backend:
    build: .
    container_name: backend
    volumes:
      - ./public/menu.json:/app/menu.json
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./public/images:/usr/share/nginx/html/images
      - ./src/css:/usr/share/nginx/html/css
      - ./src/frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/frontend/table.js:/usr/share/nginx/html/table.js
    ports:
      - "8080:80"
    depends_on:
      - admin  
      - backend
    container_name: nginx
    
  admin:
    build: ./src/admin
    ports:
      - "8082:8082"
    volumes:
      - ./public/menu.json:/app/menu.json
    depends_on:
      - backend
    container_name: admin
